'use client';
import {useMemo,useState} from 'react';
import {LayoutDashboard,FolderKanban,CheckSquare,Users,BarChart3,Settings,Search,Bell,Plus,MoreHorizontal,CalendarDays,Clock3,ChevronDown,Menu,Brain,Trash2} from 'lucide-react';

type Task={id:number,title:string,status:'Todo'|'In Progress'|'Done',priority:'High'|'Medium'|'Low',assignee:string};
const initialTasks:Task[]=[
{id:1,title:'Create landing page',status:'Todo',priority:'High',assignee:'AD'},
{id:2,title:'Set up authentication',status:'Todo',priority:'Medium',assignee:'RK'},
{id:3,title:'Build dashboard cards',status:'In Progress',priority:'High',assignee:'AD'},
{id:4,title:'Design mobile navigation',status:'In Progress',priority:'Low',assignee:'SM'},
{id:5,title:'Create project database',status:'Done',priority:'High',assignee:'RK'},
{id:6,title:'Add dark mode',status:'Done',priority:'Low',assignee:'AD'}];
const nav=[['Dashboard',LayoutDashboard],['Projects',FolderKanban],['Tasks',CheckSquare],['Team',Users],['Analytics',BarChart3],['Settings',Settings]] as const;
export default function Home(){
 const [section,setSection]=useState('Dashboard'); const [tasks,setTasks]=useState(initialTasks); const [modal,setModal]=useState(false); const [search,setSearch]=useState('');
 const filtered=useMemo(()=>tasks.filter(t=>t.title.toLowerCase().includes(search.toLowerCase())),[tasks,search]);
 function addTask(title:string,priority:Task['priority']){setTasks(x=>[...x,{id:Date.now(),title,status:'Todo',priority,assignee:'AD'}]);setModal(false)}
 function cycle(id:number){setTasks(ts=>ts.map(t=>t.id===id?{...t,status:t.status==='Todo'?'In Progress':t.status==='In Progress'?'Done':'Todo'}:t))}
 return <div className="app">
  <aside className="sidebar"><div className="brand"><span className="logo"><Brain size={19}/></span>TeamFlow</div><div className="workspace">Workspace</div><nav className="nav">{nav.map(([name,Icon])=><button key={name} className={section===name?'active':''} onClick={()=>setSection(name)}><Icon size={17}/>{name}</button>)}</nav><div className="workspace" style={{marginTop:35}}>My workspace</div><button className="nav" style={{border:0,background:'transparent',color:'#aeb7c8',padding:'11px 12px',display:'flex',gap:10,alignItems:'center'}}><FolderKanban size={17}/>Product Launch</button></aside>
  <main className="main"><header className="topbar"><div className="search"><Search size={16}/><input placeholder="Search tasks..." value={search} onChange={e=>setSearch(e.target.value)}/></div><div className="profile"><Bell size={18} color="#748097"/><div className="avatar">AD</div><span style={{fontSize:13,fontWeight:600}}>Atharva</span><ChevronDown size={14}/></div></header>
  <section className="content">
   {section==='Dashboard'&&<Dashboard tasks={tasks} onAdd={()=>setModal(true)}/>} 
   {section==='Projects'&&<Projects/>}
   {section==='Tasks'&&<Tasks tasks={filtered} onCycle={cycle} onAdd={()=>setModal(true)}/>} 
   {section==='Team'&&<Team/>}
   {section==='Analytics'&&<Analytics tasks={tasks}/>} 
   {section==='Settings'&&<SettingsPage/>}
  </section></main>
  {modal&&<TaskModal onClose={()=>setModal(false)} onCreate={addTask}/>} 
 </div>
}
function Dashboard({tasks,onAdd}:{tasks:Task[],onAdd:()=>void}){const done=tasks.filter(t=>t.status==='Done').length;return <><div className="heading"><div><h1>Good morning, Atharva 👋</h1><div className="muted">Here’s what’s happening with your projects today.</div></div><button className="primary" onClick={onAdd}><Plus size={16} style={{verticalAlign:'-3px',marginRight:5}}/>New task</button></div><div className="stats"><Stat label="Active Projects" value="12" trend="+2 this month"/><Stat label="Total Tasks" value={String(tasks.length+42)} trend="+8 this week"/><Stat label="Completed" value={String(done+28)} trend="+14% this week"/><Stat label="Overdue" value="4" trend="Needs attention" danger/></div><div className="grid"><div className="card"><h3>Recent projects</h3><Project name="Product Launch" meta="18 tasks · Updated 2h ago" progress={78}/><Project name="Mobile App" meta="24 tasks · Updated yesterday" progress={56}/><Project name="Marketing Website" meta="12 tasks · Updated 3d ago" progress={34}/></div><div className="card"><h3>Recent activity</h3><Activity text="Atharva completed Create database" time="12 min ago"/><Activity text="Riya moved Dashboard UI to In Progress" time="1h ago"/><Activity text="Sam added a comment to Mobile App" time="3h ago"/><Activity text="You created Product Launch" time="Yesterday"/></div></div></>}
function Stat({label,value,trend,danger}:{label:string,value:string,trend:string,danger?:boolean}){return <div className="card"><div className="stat-label">{label}</div><div className="stat-value">{value}</div><div className={danger?'trend':'trend'} style={danger?{color:'#dc2626'}:{}}>{trend}</div></div>}
function Project({name,meta,progress}:{name:string,meta:string,progress:number}){return <div className="project"><div><div style={{fontWeight:600,fontSize:14}}>{name}</div><div className="muted" style={{fontSize:12,marginTop:4}}>{meta}</div><div className="progress" style={{width:230}}><div className="bar" style={{width:`${progress}%`}}/></div></div><span className="pill">{progress}%</span></div>}
function Activity({text,time}:{text:string,time:string}){return <div className="activity"><div className="avatar" style={{width:30,height:30,fontSize:10}}>AD</div><div><div>{text}</div><div className="muted" style={{fontSize:11,marginTop:4}}>{time}</div></div></div>}
function Projects(){return <><div className="heading"><div><h1>Projects</h1><div className="muted">Manage your team's projects and progress.</div></div><button className="primary"><Plus size={16} style={{verticalAlign:'-3px',marginRight:5}}/>New project</button></div><div className="stats"><Stat label="All Projects" value="12" trend="Across workspace"/><Stat label="On Track" value="8" trend="67% of projects"/><Stat label="At Risk" value="3" trend="Review deadlines" danger/><Stat label="Completed" value="1" trend="This quarter"/></div><div className="card" style={{marginTop:18}}><h3>All projects</h3>{['Product Launch','Mobile App','Marketing Website','Internal Tools'].map((n,i)=><Project key={n} name={n} meta={`${18+i*4} tasks · ${i+2} members`} progress={[78,56,34,91][i]}/>)}</div></>}
function Tasks({tasks,onCycle,onAdd}:{tasks:Task[],onCycle:(id:number)=>void,onAdd:()=>void}){return <><div className="heading"><div><h1>Tasks</h1><div className="muted">Track work across your projects.</div></div><button className="primary" onClick={onAdd}><Plus size={16} style={{verticalAlign:'-3px',marginRight:5}}/>New task</button></div><div className="board">{(['Todo','In Progress','Done'] as Task['status'][]).map(status=><div className="column" key={status}><div className="column-title"><span>{status}</span><span>{tasks.filter(t=>t.status===status).length}</span></div>{tasks.filter(t=>t.status===status).map(t=><div className="task" key={t.id}><div className="task-title">{t.title}</div><div className="task-meta"><span className={`priority ${t.priority.toLowerCase()}`}>{t.priority}</span><span onClick={()=>onCycle(t.id)} style={{cursor:'pointer'}}>↻ Move</span><span className="avatar" style={{width:24,height:24,fontSize:9}}>{t.assignee}</span></div></div>)}</div>)}</div></>}
function Team(){const people=[['Atharva Diwate','Frontend Developer','AD'],['Riya Kulkarni','Product Designer','RK'],['Sam Mehta','Backend Developer','SM'],['Neha Patil','Product Manager','NP']];return <><div className="heading"><div><h1>Team</h1><div className="muted">People working in your workspace.</div></div><button className="primary"><Plus size={16} style={{verticalAlign:'-3px',marginRight:5}}/>Invite member</button></div><div className="card"><table className="table"><thead><tr><th>Member</th><th>Role</th><th>Projects</th><th>Status</th><th></th></tr></thead><tbody>{people.map((p,i)=><tr key={p[0]}><td><div style={{display:'flex',alignItems:'center',gap:10}}><span className="avatar">{p[2]}</span>{p[0]}</div></td><td>{p[1]}</td><td>{i+2}</td><td><span className="pill">Active</span></td><td><MoreHorizontal size={17}/></td></tr>)}</tbody></table></div></>}
function Analytics({tasks}:{tasks:Task[]}){const completed=tasks.filter(t=>t.status==='Done').length;return <><div className="heading"><div><h1>Analytics</h1><div className="muted">A quick view of workspace productivity.</div></div></div><div className="stats"><Stat label="Completion Rate" value={`${Math.round(completed/tasks.length*100)}%`} trend="+8.4% vs last week"/><Stat label="Avg. Cycle Time" value="2.8d" trend="0.4d faster"/><Stat label="Tasks Created" value="64" trend="+16 this week"/><Stat label="Team Velocity" value="42" trend="+12%"/></div><div className="grid"><div className="card"><h3>Weekly completion</h3><div style={{display:'flex',alignItems:'end',height:220,gap:18,padding:'20px 10px'}}>{[38,55,42,72,60,86,74].map((v,i)=><div key={i} style={{flex:1,textAlign:'center'}}><div style={{height:v*2,background:'#6366f1',borderRadius:'6px 6px 0 0'}}/><div className="muted" style={{fontSize:10,marginTop:6}}>{['Mon','Tue','Wed','Thu','Fri','Sat','Sun'][i]}</div></div>)}</div></div><div className="card"><h3>Workload</h3>{[['Atharva',82],['Riya',64],['Sam',51],['Neha',37]].map(x=><div key={x[0]} style={{margin:'17px 0'}}><div style={{display:'flex',justifyContent:'space-between',fontSize:12}}><span>{x[0]}</span><b>{x[1]}%</b></div><div className="progress"><div className="bar" style={{width:`${x[1]}%`}}/></div></div>)}</div></div></>}
function SettingsPage(){return <><div className="heading"><div><h1>Settings</h1><div className="muted">Manage workspace preferences.</div></div></div><div className="card"><h3>Workspace settings</h3><div className="field"><label>Workspace name</label><input defaultValue="TeamFlow Workspace"/></div><div className="field"><label>Workspace URL</label><input defaultValue="teamflow.local"/></div><button className="primary">Save changes</button></div></>}
function TaskModal({onClose,onCreate}:{onClose:()=>void,onCreate:(title:string,p:Task['priority'])=>void}){const [title,setTitle]=useState('');const [p,setP]=useState<Task['priority']>('Medium');return <div className="modal-bg"><div className="modal"><h2>Create task</h2><div className="field"><label>Task title</label><input autoFocus placeholder="e.g. Build authentication" value={title} onChange={e=>setTitle(e.target.value)}/></div><div className="field"><label>Priority</label><select value={p} onChange={e=>setP(e.target.value as Task['priority'])}><option>High</option><option>Medium</option><option>Low</option></select></div><div className="modal-actions"><button className="secondary" onClick={onClose}>Cancel</button><button className="primary" disabled={!title.trim()} onClick={()=>onCreate(title.trim(),p)}>Create task</button></div></div></div>}
